## YAML Template.
---
server:
  port: 0

spring:
  application:
    name: EBULLETIN-METIER-1
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ebulletin
  devtools:
    restart:
      enabled: true
  jpa:
    properties:
      hibernate:
        show_sql: false
    hibernate:
      ddl-auto: update
      jdbc.lob.non_contextual_creation: true
      default_schema: public
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/cnamudb_test
    username: postgres
    password: admin

keycloak:
  realm: ebulletin
  #auth-server-url: https://ebulletin.finances.bf/auth
  auth-server-url: http://localhost:8080/
  resource: ebulletin-backend
  credentials:
    secret: yROutTPZ7XZp8p0wHXAAGXSmh2ldoigk
  use-resource-role-mappings: true
  principal-attribute: preferred_username
  public-client: true
  bearer-only: true
  cors: true
  enabled: true

#config de connexion au registry eureka
eureka:
  client:
    register-with-eureka: true
    fectch-registry: false
    service-url:
        defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true
---
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
#log app
logging:
  level:
    ROOT: INFO
    bf.gov.finances.dgsi.ebulletinmetier1: 
      - DEBUG
      - INFO