server:
  port: 8761

eureka: 
  client:
    register-with-eureka: false
    fectch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0

management:
  endpoints:
    web:
      exposure:
        include: '*'
